INSERT INTO to_do VALUES (1, 'SAMPLE1', 'SAMPLE MESSAGE1', CURRENT_TIMESTAMP);
INSERT INTO to_do VALUES (2, 'SAMPLE2', 'SAMPLE MESSAGE2', CURRENT_TIMESTAMP);
INSERT INTO to_do VALUES (3, 'SAMPLE3', 'SAMPLE MESSAGE3', CURRENT_TIMESTAMP);
